apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce
    service: advertisements
  name: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      service: advertisements
  strategy: {}
  template:
    metadata:
      labels:
        app: ecommerce
        service: advertisements
    spec:
      containers:
      - image: "shocnt/ads-service:latest"
        imagePullPolicy: IfNotPresent
        name: advertisements
        command: ["flask"]
        args: ["run", "--port=5002", "--host=0.0.0.0"]
        env:
          - name: FLASK_APP
            value: "ads.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: pw
                name: db-password
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_HOST
            value: "db"
        ports:
        - containerPort: 5002
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecommerce
    service: advertisements
  name: advertisements
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: ecommerce
    service: advertisements
