apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce
    service: discounts
  name: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      service: discounts
  strategy: {}
  template:
    metadata:
      labels:
        app: ecommerce
        service: discounts
    spec:
      containers:
      - image: "shocnt/discounts-service:latest"
        imagePullPolicy: IfNotPresent
        name: discounts
        command: ["flask"]
        args: ["run", "--port=5001", "--host=0.0.0.0"]
        env:
          - name: FLASK_APP
            value: "discounts.py"
          - name: FLASK_DEBUG
            value: "1"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: pw
                name: db-password
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_HOST
            value: "db"
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 5001
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecommerce
    service: discounts
  name: discounts
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: ecommerce
    service: discounts
  type: ClusterIP
